name: berdi
channels:
  - defaults
dependencies:
  - python=3.7
  - cudatoolkit=10.1
  - cudnn=7.6
  - pip
  - pip:
    - wheel==0.37.0
    - PyPDF2==1.26.0
    - tika==1.24
    - python-dotenv==0.19.2
    - SQLAlchemy==1.4.27
    - camelot-py[cv]==0.10.1
    - fitz==0.0.1.dev2
    - mysqlclient==2.0.3
    - pyodbc==4.0.32
    - pandas==1.3.4
    - beautifulsoup4==4.10.0
    - nltk==3.6.5
    - scikit-learn==1.0.1
    - transformers==4.12.3
    - tqdm==4.62.3
    - torch==1.10.0
    - numpy==1.21.4
    - spacy==3.2.0
    - ipython==7.30.0
    - fuzzywuzzy==0.18.0
