INSERT INTO Username_BERDI.ValueComponent (ValueComponent)
VALUES ('Landscape, terrain, and weather'),
('Soil'),
('Plants'),
('Water'),
('Fish'),
('Wetlands'),
('Wildlife'),
('Species at Risk'),
('Greenhouse gas emissions'),
('Air emissions'),
('Noise'),
('Electricity and electromagnetism'),
('Proximity to people'),
('Archaeological, paleontological, historical, and culturally significant sites and resources'),
('Human access to boats and waterways'),
('Indigenous land, water, and air use'),
('Impact to social and cultural well-being'),
('Impact to human health and viewscapes'),
('Social, cultural, economic infrastructure and services'),
('Economic Offsets and Impact'),
('Environmental Obligations'),
('Treaty and Indigenous Rights');